language: python
cache: pip
python:
  - '2.7'
  - '3.4'
  - '3.6'
env:
  - DB="POSTGRESQL"
  - DB="MYSQL"
services:
  - mysql
  - postgres
before_install:
  - pip install codecov
  - if [[ $DB = 'POSTGRESQL' ]]; then pip install -q psycopg2; fi
  - if [[ $DB = 'MYSQL' ]]; then pip install -q mysqlclient; fi
install:
  - pip install -e git+https://github.com/modoboa/modoboa#egg=modoboa
  - pip install -q factory-boy testfixtures
  - python setup.py -q develop
before_script:
  - if [[ $DB = 'POSTGRESQL' ]]; then psql -c 'create database modoboa_test;' -U postgres; fi
  - if [[ $DB = 'MYSQL' ]]; then mysql -e "create database IF NOT EXISTS modoboa_test;" -uroot; fi
  - if [[ $DB = 'MYSQL' ]]; then mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'modoboa'@'localhost' IDENTIFIED BY 'modoboa';" -uroot; fi
script:
  - cd test_project
  - coverage run --source ../modoboa_dmarc manage.py test modoboa_dmarc
after_success:
  - codecov
before_deploy:
  - cd ../modoboa_dmarc
  - django-admin compilemessages
  - cd ..
deploy:
  provider: pypi
  user: tonio
  password:
    secure: FUgRGH8DZ6+89/GW4tY37dMT+pyO32BpQ3uCmRBsC7lVQO+R+ILAE5lUa+K5lzI5YMLFILpqKi6Q2z+uCsW0VYn1BHLnpZX+Sjedgu2/TOsQPTuxXCPzpxXl+RyS6uknT/3srGmtVS8t6p3bVQMddbQFLlFvKapKrPMDkIRmQaH+nbOmRbarJrD13DSZwxARrga1sJqqxpBdtw0P1ZZt7jb+vmTENWBKY7NRMBMQ75v7Jt/faaN9CgczX9i4DRsHdTyC7ReZMcb+Xdq9Tgd37ME1mPQyjLbnAt4tM9OIuLMnaYtb43lhGlYxqVp+WyASvXnfYREiLobr5L4D5ZMuCB5KJRdRNyD244B7KN9zDdqkv8iBlTYLvJveNk/mOHwPrAbmnKOQmtybkF1a4MWbS8OWfrP0eEKQ4ffoPt0NdkZN3Ojhr+w3OXVADvQYO4OQ5THJOgnJjx/jQWZ2V3/hb4scdsyXSbAIrmoN0k8IZYrF696dy1btiXVP/zj15AnAC6zCK31xSvjsUaTlPm1aRuMvzXWohyx+xy3lJZjRwBtj1nkguwbLG+g9y0lSs0NQgxXevWmCdZfshxG0bGymuCNyZRjs4lp2NPAbCpRHVenY7KEYnoCWIPi/9XQT3OkbRT+8Y6b+DltsbKuSlf9YFJq4ukDntOvR+lmTqpxe3HU=
  skip_cleanup: true
  on:
    tags: true
    python: '3.6'
